### ISSUE TITLE
Add toggle setting to use a single Octobox tab

### ISSUE THREAD

**Issue by pradyunsg** [tfrommen/octobox-web-extension#1]
#### Steps to Reproduce

1. Open octobox.io in a tab (optionally pin the tab)
1. Open GitHub and click the bell icon

#### What I Expected

I will get switched to the existing open tab with Octobox open.

#### What Happened Instead

The current tab got redirected to octobox.io.

**Comment by pradyunsg** [comment]
It's possible to do this with HTML + JS on page: https://stackoverflow.com/a/36727173/1931274

**Comment by tfrommen** [comment]
Thanks for this. However, this not how I want the extension to behave.

Assuming you are using the _official_ Octobox at [https://octobox.io](https://octobox.io), then you will see a GitHub icon link in the top bar. This icon, just like any other link to GitHub will **not** open in a new tab (which is the default for Octobox). Instead, it will change to GitHub in the current tab. This means that you will treat your Octobox inbox just like the regular notifications page on GitHub is being used.

If you don't want to do this, you can always `Ctrl`- or `Cmd`-click it to have it open in a new tab.

Switching to an existing Octobox tab, however, is not possible, by design.

✌️

**Comment by pradyunsg** [comment]
Sure. Fair enough.

Would you be willing to put a toggle for this? I usually keep my octobox open in a pinned tab and it would be nice if I could have this behavior -- switch to that tab when I click on the notifications icon.

**Comment by tfrommen** [comment]
Hm, this is an option, yeah. I'll re-open, and have a think about this. 🙂

**Comment by pradyunsg** [comment]
Awesome! Thanks. ^>^

**Comment by pradyunsg** [comment]
a _very_ gentle ping on this.

**Comment by pradyunsg** [comment]
Closing since I no longer use Octobox. Thanks @tfrommen for the discussion here!
